### ISSUE TITLE
CSV Headers are newline separated

### ISSUE THREAD

**Issue by arichiardi** [wbaumann/SmartReceiptsLibrary#14]
Hello, very very good discovery of my Sunday :+1: Good job!

There is a little bug when you include the CSV headers are included for example:

```
Date,
Name,
Price,
Currency,
Tax,
Comment,
Category Name,
Image Path,
Receipt ID,
Report Name,
Report Start Date,
Report End Date,
08-01-2016, ...
```

Therefore CSV parsers fail on that.

**Comment by wbaumann** [comment]
Great catch (and glad to here you like the app :) )! Working on a fix right now and will have something pushed locally and to Google Play shortly. Don't hesitate to open any other issues that you might find in the future!

**Comment by arichiardi** [comment]
It is weird because it does not happen all the time, so the fix might be tricky but I am here to test it don't worry (former Android dev) ;)

**Comment by wbaumann** [comment]
No problem. 99% sure I found it and fixed it (just swapped the order of the comma and new lines characters), so I should have a fix ready soon.

**Comment by wbaumann** [comment]
Fixed the issue. Should be pushed back to Google Play (and github). Thanks!

**Comment by arichiardi** [comment]
Thank you!
