### ISSUE TITLE
mileage (as lines, not as separate table) in PDF but not in CVS

### ISSUE THREAD

**Issue by pcfe** [wbaumann/SmartReceiptsLibrary#17]
If I switch
- OFF Include Distance Table
- ON  Report on Daily Distance

I get a PDF report like expected, but on the CSV the distance lines are 
missing.

Smart Receipts Plus 3.3.4.1

**Comment by wbaumann** [comment]
Appreciate the feedback on this item. Will be sure to include this in  the next release

**Comment by wbaumann** [comment]
Resolving this item as fixed in the `4.4.0` release

**Comment by wbaumann** [comment]
Whoops - reopening. The code was never pushed for some reason but working on it now. Will address soon!

**Comment by wbaumann** [comment]
Fixed in this PR:

- https://github.com/wbaumann/SmartReceiptsLibrary/pull/53

Will resolve this when the fix is included with the `4.6.0` release
