### ISSUE TITLE
When Runing I get Fire Department

### ISSUE THREAD

**Issue by torqueing** [wbaumann/SmartReceiptsLibrary#190]
When running this in the Android emulator it comes up as the Fire Service Reciepts. Is there any way to remove/stop that and just have the good old plain SmartReceipts?

Also I get these errors, I think they are from the oss-licenses-plugin:

API 'variant.getPreBuild()' is obsolete and has been replaced with 'variant.getPreBuildProvider()'.
API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.

**Comment by wbaumann** [comment]
Where are you building from? Android Studio? Does this article help:

https://stackoverflow.com/questions/45746049/how-to-run-different-product-flavors-in-android-studio

**Comment by torqueing** [comment]
Thank you, that worked! I am very new to app development!

**Comment by wbaumann** [comment]
Glad that worked!
