### ISSUE TITLE
Move Receipts between Reports

### ISSUE THREAD

**Issue by wompydomp** [wbaumann/SmartReceiptsLibrary#4]
Hi,

I've a little feature request. I often fill out a receipt in the wrong expense report and would like to move it to a different one. Would that be possible?

Thank you for this great app. With OCR this would be a killer app. Are you aware that fdroid still publishes your 2.2.1 version?

Kind Regards,
Jo

**Comment by wbaumann** [comment]
Closing this issue as now you can move receipts between reports
