### ISSUE TITLE
automatic backup to cloud

### ISSUE THREAD

**Issue by edgimar** [wbaumann/SmartReceiptsLibrary#5]
It would be a nice feature if receipts and expense metadata could be automatically synced to some folder on dropbox or Google drive (or to some sftp location).  Otherwise, unless you are frequently sending yourself reports, losing your phone could mean losing your expense records.

**Comment by wbaumann** [comment]
This is resolved as of the latest release! We now support Google Drive. I'm planning to continue adding more providers as we go along as well.
