### ISSUE TITLE
CSV report sending empty column

### ISSUE THREAD

**Issue by arichiardi** [wbaumann/SmartReceiptsLibrary#73]
Hi @wbaumann :smile: 

As usual very nice work here! I noticed a bug with the csv report. Basically it exports something like:

```
Date,Name,Price,Currency,Category Code,Category Name,Receipt ID,Comment,
11/4/17,"My item",45.59,CAD,OTHS,Other Supplies,51,,
```

You might notice the ending `,` at the end. This will translate to an empty column.

Probably an easy fix, just wanted to report it ;)

Thanks a lot for your immense work!

EDIT: version is `4.10.0.403`

**Comment by wbaumann** [comment]
Hi @arichiardi - Really appreciate your feedback here :)

Had you entered a value for the `Comment` field? Or did you mean that there was a trailing comma at the end of each row?

Thanks!

**Comment by arichiardi** [comment]
So she Comment field is empty and also the last of the columns in the column list.

It seems that the CSV has some sort of +1 error in that it always adds an empty column to each row.

Not sure though.

**Comment by wbaumann** [comment]
Ah I see what you mean. The trailing `,` at the end. 

Let me look into getting this fixed for you. Thanks so much for bringing this to my attention!

**Comment by wbaumann** [comment]
Thank you again for letting me know about this item. It is fixed in:

https://github.com/wbaumann/SmartReceiptsLibrary/commit/c7789e94a84bec993bd41e5e2e88a0f4e83e1e5a

This will be generally available in the `4.11.x` release. I will hold off on closing it until that release is completed. Thanks!

**Comment by arichiardi** [comment]
Awesome thanks!

**Comment by wbaumann** [comment]
Closing now that `4.11.x` is released (or was released a few months ago)!
