### ISSUE TITLE
Receipt Name filled by Category Name on click

### ISSUE THREAD

**Issue by arichiardi** [wbaumann/SmartReceiptsLibrary#74]
Hi again :smile:!

so I will try to explain the bug: when I click on the Category Name and select a new one, the Name of the receipt is basically filled with the selected category.

This was found in version is `4.10.0.403`

**Comment by wbaumann** [comment]
Thanks for reaching out to us! If you open the settings menu, could you see if the "Match Name to Category" is set? If so, can you uncheck this and see if that fixes it? Thanks!

**Comment by arichiardi** [comment]
Ok let me check that

**Comment by arichiardi** [comment]
Thanks that solves!

**Comment by wbaumann** [comment]
@arichiardi Great! Thank you :)
