### ISSUE TITLE
App crashes when I open the open 

### ISSUE THREAD

**Issue by pzdawood** [wbaumann/SmartReceiptsLibrary#78]
### Actual behaviour
When I open the smart receipts pro app suddenly crashes.
### How to reproduce
* Download the smart receipts pro app from F-driod.
* Install this app.
* Open smart receipts pro app suddenly crashes.
* Browser: smart receipts pro.
* Version:1.1.1
* Operating system:7.1.2
### Recording of the bug
https://youtu.be/OdrPkW7U2-s

**Comment by wbaumann** [comment]
Hi @pzdawood ,

Your posted video was taken down I think:

> This video has been removed for violating YouTube's Terms of Service.

More generally, however, I believe this crash stems from using a legacy version of the app. When adding some newer features, I didn't properly modularize all of our components (eg Google Drive backups), which depend on some non-FOSS libraries. I have been working towards correcting this as part of:

* https://github.com/wbaumann/SmartReceiptsLibrary/issues/66

Would you be comfortable if I close this item in favor of the above? The larger fix will require some updates to the newer versions (with all fixes) to make the compatible again with F-Droid. Thanks!

**Comment by pzdawood** [comment]
Yes sir close
