### ISSUE TITLE
Build error with 3.3.2: No resource found that matches the given name

### ISSUE THREAD

**Issue by RealRancor** [wbaumann/SmartReceiptsLibrary#8]
Hi,

when trying to build the app (3.3.2 tag) from source it currently fails with this message:

```
/usr/src/wb.receiptspro/AndroidCamera/res/layout-port/pano_review.xml:70: error: Error: No resource found that matches the given name (at 'id' with value '@id/pano_review_cancel_button')
```

I can't find any infos on the net what this is causing. Are there any libraries needed to linked / described / included in this project?

**Comment by wbaumann** [comment]
There shouldn't be anything outside of what's defined in the gradle build. For repro purposes, how are you trying to build the app? Using the gradle wrapper from the command line? Additionally, can you test if you can build the develop branch? It's possible that I forgot to cherry-pick a fix over.

**Comment by RealRancor** [comment]
Hi,

and thanks for your reply. The release 3.3.2 is not migrated to gradle so i had used ant from command line and also with the linked f-droid build receipt above to build the app.

Both have failed with the posted error.

**Comment by wbaumann** [comment]
Ah - my apologies for not recognizing this from before. I've had the
develop branch on gradle for so long, that I just assumed 3.3.2 was as
well. I'll investigate this further and see what I changes I need to
cherry-pick over to get this working. Will get back to you shortly.

**Comment by wbaumann** [comment]
I went ahead and pushed my develop code over to the master branch for version 3.3.3. It's the same as what's rolling out in the app store now and should work with gradle (as that's what I'm using now). Does that work for you?

**Comment by RealRancor** [comment]
Hi,

and sorry for the delay. Building 3.3.3 now worked without a problem. So closing this for now.
