### ISSUE TITLE
When do the uploaded receipts from S3 get deleted?

### ISSUE THREAD

**Issue by neowulf** [wbaumann/SmartReceiptsLibrary#88]
Hi, I was evaluating your product and decided to read some of the source code. I see that the receipts get [uploaded to S3](https://github.com/wbaumann/SmartReceiptsLibrary/blob/master/app/src/main/java/co/smartreceipts/android/ocr/OcrManager.java#L111) but it's not clear when those receipts get deleted after they are processed. When and how do the uploaded receipt images get deleted?

**Comment by wbaumann** [comment]
Hey neowulf,

Thank you for the feedback. You are correct that receipts are uploaded to S3 if you're using the OCR functionality (but only if you're using this). Here's the rough flow:

- The user initiates an OCR scan
- We upload the image to S3
- We submit a service request to our backend with the S3 URL path, which then sends this request to [taggun.io](https://www.taggun.io/) (a third party that performs the scans). We approach it in this way to avoid including the taggun API KEY in the Android APK to prevent access via de-compilation
- We await the results and return those to the user

At this point, there are two parties that you need to trust: us (Smart Receipts) and Taggun. On our side, we have configured a rule in S3, which automatically deletes these files after 1 day:

https://s3.amazonaws.com/smartreceipts/Screenshots/S3OcrDeleteSettings.png

I've attached a screenshot of this (above), which I acknowledge still requires trust. Are you familiar with S3 / do you know if it's possible to make a rule (i.e. the OCR deletion one above) world read-able? I like to let you formally verify, but I'm not sure how to do so without providing larger scale access.

On the taggun side, they support an [incognito](https://github.com/wbaumann/SmartReceiptsLibrary/blob/115dc93279d83e6bdb0763d64ced0048f28b134b/app/src/main/java/co/smartreceipts/android/ocr/apis/model/RecongitionRequest.java#L12) flag, which prevents these images from being saved. More generally, you can find their privacy policy here:

- https://www.taggun.io/privacy/

Does that help? The **TL;DR** version is that we use S3 bucketing rules to automatically delete any image that is older than a day. I'm more than happy to look into other approaches if you have suggestions too. Thanks!

**Comment by wbaumann** [comment]
@dosch I do aim to support others at some point, but truthfully it's much further back in our backlog. If you're curious and/or want to build the functionality yourself, I can walk you through exactly how to do so? Thanks!

**Comment by neowulf** [comment]
Thank you for the details!
