### ISSUE TITLE
Using mixed case in gradle files causing build problems on linux systems

### ISSUE THREAD

**Issue by RealRancor** [wbaumann/SmartReceiptsLibrary#9]
Hi,

on systems with case sensitivity like linux the following lines:

https://github.com/wbaumann/SmartReceiptsLibrary/blob/master/settings.gradle#L1
https://github.com/wbaumann/SmartReceiptsLibrary/blob/master/settings.gradle#L6
https://github.com/wbaumann/SmartReceiptsLibrary/blob/master/SmartReceiptsLibrary/build.gradle#L6
https://github.com/wbaumann/SmartReceiptsLibrary/blob/master/SmartReceiptsFree/build.gradle#L6
https://github.com/wbaumann/SmartReceiptsLibrary/blob/master/SmartReceiptsPRO/build.gradle#L5

are causing build failures because the case doesn't match the name of the folder on the repos/filesystem. So for example:

include ':smartReceiptsFree'

should be:

include ':SmartReceiptsFree'

**Comment by wbaumann** [comment]
Good catch. This occurred because the Android gradle conversation defaults to having all modules start with lower case characters. On my system (OSX) at least, git is case insensitive, so it doesn't pick up the differences. 

I'll fix this up to standardize.

**Comment by wbaumann** [comment]
Fixed in the develop branch a little while ago. Will resolve when merged to master

**Comment by wbaumann** [comment]
Should be merged and resolved now
